version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER:-objecttypes}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-objecttypes}

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=objecttypes.conf.docker
      - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$15d}
      - ALLOWED_HOSTS=*
    ports:
      - 8000:8000
    depends_on:
      - db
