openapi: 3.0.0
info:
  title: objecttypes API
  description: An API to access Object types
  version: 0.1.0
security:
- Token: []
paths:
  /objecttypes:
    get:
      operationId: objecttype_list
      description: ''
      parameters:
      - name: dataClassification
        in: query
        description: Confidential level of the object type
        required: false
        schema:
          type: string
          enum:
          - open
          - intern
          - confidential
          - strictly_confidential
      responses:
        '200':
          description: OK
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectType'
        '400':
          description: Bad request
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidatieFout'
        '401':
          description: Unauthorized
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '403':
          description: Forbidden
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '406':
          description: Not acceptable
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '409':
          description: Conflict
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '410':
          description: Gone
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '415':
          description: Unsupported media type
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '429':
          description: Too many requests
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '500':
          description: Internal server error
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
      tags:
      - objecttypes
    parameters: []
  /objecttypes/{uuid}:
    get:
      operationId: objecttype_read
      description: ''
      parameters:
      - name: If-None-Match
        in: header
        description: "Voer een voorwaardelijk verzoek uit. Deze header moet \xE9\xE9\
          n of meerdere ETag-waardes bevatten van resources die de consumer gecached\
          \ heeft. Indien de waarde van de ETag van de huidige resource voorkomt in\
          \ deze set, dan antwoordt de provider met een lege HTTP 304 request. Zie\
          \ [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match)\
          \ voor meer informatie."
        required: false
        examples:
          oneValue:
            summary: "E\xE9n ETag-waarde"
            value: '"79054025255fb1a26e4bc422aef54eb4"'
          multipleValues:
            summary: Meerdere ETag-waardes
            value: '"79054025255fb1a26e4bc422aef54eb4", "e4d909c290d0fb1ca068ffaddf22cbd0"'
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: De ETag berekend op de response body JSON. Indien twee
                resources exact dezelfde ETag hebben, dan zijn deze resources identiek
                aan elkaar. Je kan de ETag gebruiken om caching te implementeren.
              schema:
                type: string
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectType'
        '401':
          description: Unauthorized
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '403':
          description: Forbidden
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '404':
          description: Not found
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '406':
          description: Not acceptable
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '409':
          description: Conflict
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '410':
          description: Gone
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '415':
          description: Unsupported media type
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '429':
          description: Too many requests
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '500':
          description: Internal server error
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van
                een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
      tags:
      - objecttypes
    parameters:
    - name: uuid
      in: path
      description: Unique identifier (UUID4)
      required: true
      schema:
        type: string
        format: uuid
tags:
- name: objecttypes
  description: ''
servers:
- url: https://example.com/api/v1
components:
  securitySchemes:
    Token:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    ObjectVersion:
      type: object
      properties:
        version:
          title: Versie
          description: Integer version of the OBJECTTYPE
          type: integer
          maximum: 32767
          minimum: 0
        publicationDate:
          title: Publicationdate
          description: Date of Version publication
          type: string
          format: date
        status:
          title: Status
          description: Status of the object type version
          type: string
          enum:
          - published
          - draft
          - deprecated
          readOnly: true
        jsonSchema:
          title: JSON schema
          description: JSON schema for Object validation
          type: object
    ObjectType:
      required:
      - name
      - namePlural
      - versions
      type: object
      properties:
        url:
          title: Url
          description: URL-referentie naar dit object. Dit is de unieke identificatie
            en locatie van dit object.
          type: string
          format: uri
          readOnly: true
          maxLength: 1000
          minLength: 1
        name:
          title: Naam
          description: Name of the object type
          type: string
          maxLength: 100
          minLength: 1
        namePlural:
          title: Nameplural
          description: Plural name of the object type
          type: string
          maxLength: 100
          minLength: 1
        description:
          title: Description
          description: The description of the object type
          type: string
          maxLength: 1000
        dataClassification:
          title: Dataclassification
          description: Confidential level of the object type
          type: string
          enum:
          - open
          - intern
          - confidential
          - strictly_confidential
        maintainerOrganization:
          title: Maintainerorganization
          description: Organization which is responsible for the object type
          type: string
          maxLength: 200
        maintainerDepartment:
          title: Maintainerdepartment
          description: Business department which is responsible for the object type
          type: string
          maxLength: 200
        contactPerson:
          title: Contactperson
          description: Name of the person in the organization who can provide information
            about the object type
          type: string
          maxLength: 200
        contactEmail:
          title: Contactemail
          description: Email of the person in the organization who can provide information
            about the object type
          type: string
          maxLength: 200
        source:
          title: Source
          description: Name of the system from which the object type originates
          type: string
          maxLength: 200
        updateFrequency:
          title: Updatefrequency
          description: Indicates how often the object type is updated
          type: string
          enum:
          - real_time
          - hourly
          - daily
          - weekly
          - monthly
          - yearly
          - unknown
        providerOrganization:
          title: Providerorganization
          description: Organization which is responsible for publication of the object
            type
          type: string
          maxLength: 200
        documentationUrl:
          title: Documentationurl
          description: Link to the documentation for the object type
          type: string
          format: uri
          maxLength: 200
        labels:
          title: Labels
          description: Key-value pairs of keywords related for the object type
          type: object
        versions:
          type: array
          items:
            $ref: '#/components/schemas/ObjectVersion'
    Fout:
      required:
      - code
      - title
      - status
      - detail
      - instance
      type: object
      properties:
        type:
          title: Type
          description: URI referentie naar het type fout, bedoeld voor developers
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: Extra informatie bij de fout, indien beschikbaar
          type: string
          minLength: 1
        instance:
          title: Instance
          description: URI met referentie naar dit specifiek voorkomen van de fout.
            Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
          type: string
          minLength: 1
    FieldValidationError:
      required:
      - name
      - code
      - reason
      type: object
      properties:
        name:
          title: Name
          description: Naam van het veld met ongeldige gegevens
          type: string
          minLength: 1
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        reason:
          title: Reason
          description: Uitleg wat er precies fout is met de gegevens
          type: string
          minLength: 1
    ValidatieFout:
      required:
      - code
      - title
      - status
      - detail
      - instance
      - invalid_params
      type: object
      properties:
        type:
          title: Type
          description: URI referentie naar het type fout, bedoeld voor developers
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: Extra informatie bij de fout, indien beschikbaar
          type: string
          minLength: 1
        instance:
          title: Instance
          description: URI met referentie naar dit specifiek voorkomen van de fout.
            Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.
          type: string
          minLength: 1
        invalid_params:
          type: array
          items:
            $ref: '#/components/schemas/FieldValidationError'
